version: '3'
services:
  rpwr-assignments:
    image: intel4coro/artnie-2drpwr-2dassignments-a6f480:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
    privileged: true
    command: jupyter lab --NotebookApp.token=''
    volumes:
      - ./:/home/jovyan/rpwr-assignments

    # for windows and mac, use 'network_mode: bridge'
    # network_mode: host
    # environment:
    #   - ROS_IP=localhost  # change localhost to your wifi IP
    #   - ROS_MASTER_URI=http://localhost:11311  # change 'localhost' to TURTLE IP

